// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xutzfnriqebrsvzfevwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1dHpmbnJpcWVicnN2emZldndkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NzIzODYsImV4cCI6MjA3MjI0ODM4Nn0.6eKoBnxqbRQrJbRNX25JRTmtLxdXENW9AG2TCNM55JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});